[package]
name = "k4fq"
version = "0.1.0"
edition = "2021"
rust-version = "1.84.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0"
home = '0.5.3'
indicatif = "0.17.0-rc.10"
predicates = "2.0.0"
rdkafka = { version = "0.28", features = ["cmake-build"] }
serde = "1.0"
serde_json = "1.0"
erased-serde = "0.3"
shaku = "0.6.1"
config = "0.11"
rayon = '1.5'
crossbeam = '0.8'
tokio = { version = "1", features = ["full"] }
do-notation = "0.1"
itertools = "0.10"

[dev-dependencies]
# latest version - 0.12.0 doesn't contain kafka, so I used latest dev instead
#testcontainers = { git="https://github.com/testcontainers/testcontainers-rs.git", ref="4b6b59f8fccd51cca812662df1701a3186a87b1f" }
testcontainers = '0.13'

log = "0.4"
log4rs = "1"
assert_cmd = "2.0"

mockall = "0.11"

futures = '0.3'
